# Generated by Django 5.2.6 on 2025-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('artist', models.CharField(max_length=100, verbose_name='Artista')),
                ('album', models.CharField(blank=True, max_length=100, null=True, verbose_name='Álbum')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Imagen de portada')),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('classical', 'Clásica'), ('electronic', 'Electrónica'), ('hiphop', 'Hip Hop'), ('reggaeton', 'Reggaeton'), ('latin', 'Latina'), ('other', 'Otro')], max_length=20, verbose_name='Género')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duración')),
                ('keywords', models.CharField(help_text='Palabras clave separadas por comas', max_length=255, verbose_name='Palabras clave')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
