# Generated by Django 5.2.6 on 2025-09-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='cover_image',
            field=models.CharField(default='https://via.placeholder.com/150', verbose_name='Imagen de portada'),
        ),
    ]
