# Generated by Django 5.2.6 on 2025-09-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open', '0002_alter_cancion_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name': 'Canción', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterField(
            model_name='cancion',
            name='slug',
            field=models.CharField(blank=True, max_length=220, unique=True),
        ),
    ]
