# Generated by Django 5.2.6 on 2025-09-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.TextField()),
                ('asunto', models.CharField(choices=[('trabajo', 'Oferta de Trabajo'), ('proyecto', 'Propuesta de Proyecto'), ('consulta', 'Consulta'), ('otro', 'Otro')], max_length=20)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
