# Generated by Django 5.2.6 on 2025-09-21 04:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactame',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AddField(
            model_name='contactame',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de envío'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactame',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
        migrations.AlterField(
            model_name='contactame',
            name='asunto',
            field=models.CharField(choices=[('trabajo', 'Oferta de Trabajo'), ('proyecto', 'Propuesta de Proyecto'), ('consulta', 'Consulta'), ('otro', 'Otro')], max_length=20, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='contactame',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contactame',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contactame',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='contactame',
            name='telefono',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
