# Generated by Django 5.2.6 on 2025-09-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactame', '0002_alter_contactame_options_contactame_fecha_envio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactame',
            old_name='telefono',
            new_name='phone',
        ),
    ]
